services:
  # MinIO - Data Lake
  minio:
    image: minio/minio:latest
    container_name: sp500-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - sp500-network

  # PostgreSQL - Serving Layer
  postgres:
    image: postgres:16
    container_name: sp500-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - sp500-network

  # MinIO initialization
  minio-init:
    image: minio/mc:latest
    container_name: sp500-minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
    entrypoint: >
      /bin/sh -c "
      until mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo 'Waiting for MinIO...';
        sleep 2;
      done;

      mc mb --ignore-existing minio/${MINIO_BUCKET};

      echo 'MinIO bucket initialized successfully';
      "
    networks:
      - sp500-network

  # Ingestion
  ingestion-service:
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    container_name: sp500-ingestion
    depends_on:
      minio-init:
        condition: service_completed_successfully
    environment:
      #DATASET_PATH: /app/data/sp500_stock_data.csv
      DATASET_PATH: ${SP_500_DATA_PATH}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
    volumes:
      - ./data:/app/data:ro
    networks:
      - sp500-network

  # Processing - Apache Spark
  processing-service:
    build:
      context: ./processing-service
      dockerfile: Dockerfile
    container_name: sp500-processing
    depends_on:
      ingestion-service:
        condition: service_completed_successfully
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
    networks:
      - sp500-network

  # PostgreSQL Loader - Serving Layer
  postgres-loader-service:
    build:
      context: ./postgres-loader-service
      dockerfile: Dockerfile
    container_name: sp500-postgres-loader
    depends_on:
      processing-service:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      # MinIO
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}

      # PostgreSQL
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - sp500-network

# Volumes
volumes:
  minio_data:
  postgres_data:


# Network
networks:
  sp500-network:
    driver: bridge